name: ci

on:
  push:
    branches:
      - main
      - feat/*
      - fix/*
      - chore/*
      - update/*
  pull_request:
    branches:
      - main
      - dev

jobs:
  style_checks:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm run eslint \"./**/*.{ts,tsx}\"
      - run: npm run prettier --check "./**/*.{ts,tsx}"
