name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  jobs:
    check_stylings:
    name: Check Stylings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
        run: npm ci
        run: eslint \"./**/*.{ts,tsx}\"
        run: 'prettier --check "./**/*.{ts,tsx}"'
