name: ci

on:
  push:
    branches:
      - main

jobs:
  style_checks:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: eslint \"./**/*.{ts,tsx}\"
      - run: prettier --check "./**/*.{ts,tsx}"
