name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: eslint \"./**/*.{ts,tsx}\"
      - name: Run Prettier Check
        run: 'prettier --check "./**/*.{ts,tsx}"'
