name: Build Docker-Image

on:
  push:
    branches: [main, feat/add-terraform]
  pull_request:
    branches: [main, feat/add-terraform]

jobs:
  release:
    name: Build Docker-Image and Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west6-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push to Google Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            ZITADEL_ISSUER=${{ secrets.ZITADEL_ISSUER }}
            ZITADEL_CLIENT_ID=${{ secrets.ZITADEL_CLIENT_ID }}
            NEXT_PUBLIC_QWACKER_API_URL=${{ secrets.NEXT_PUBLIC_QWACKER_API_URL }}
            NPM_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: |
            europe-west6-docker.pkg.dev/bytelight-app/bytelightapp/imic:latest
