name: Build Docker-Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-dependencies:
    name: Build Docker-Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_BYTELIGHT }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_QWACKER_API_URL: ${{ secrets.NEXT_PUBLIC_QWACKER_API_URL }}
          ZITADEL_ISSUER: ${{ secrets.ZITADEL_ISSUER }}
          ZITADEL_CLIENT_ID: ${{ secrets.ZITADEL_CLIENT_ID }}
        run: |
          docker build \
           --build-arg NPM_TOKEN=${{ secrets.GITHUB_TOKEN }} \
           -e NEXTAUTH_URL="${NEXTAUTH_URL}" \
           -e NEXTAUTH_SECRET="${NEXTAUTH_SECRET}" \
           -e NEXT_PUBLIC_QWACKER_API_URL="${NEXT_PUBLIC_QWACKER_API_URL}" \
           -e ZITADEL_ISSUER="${ZITADEL_ISSUER}" \
           -e ZITADEL_CLIENT_ID="${ZITADEL_CLIENT_ID}" \
           --tag app-bytelight:$(date +%s) \
           .
