name: Build Docker-Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-dependencies:
    name: Build Docker-Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build \
           --build-arg NPM_TOKEN=${{ secrets.GITHUB_TOKEN }} \
           --tag app-bytelight:$(date +%s) \
           .
