name: TFLint, ESLint & Prettier

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  style_checks:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Authenticate with private NPM package
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint and Prettier
        run: npm run style-check
      - name: Check linting of Terraform files
        uses: devops-infra/action-tflint@v0.3
